name: Build and Deploy

on: 
  workflow_dispatch:

jobs:
  app_build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Compile
        run: |
          echo "Compiling the application..."
      
  container_build:
    name: Build Container
    runs-on: ubuntu-latest
    needs: app_build
    steps:
      - name: Build Docker Image
        run: |
          echo "Building the Docker image..."
  
  
  deploy_to_dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: container_build
    steps:
      - name: Deploy to Dev
        run: |
          echo "Deploying to Dev..."

  deploy_to_int:
    name: Deploy to Int
    runs-on: ubuntu-latest
    needs: container_build
    steps:
      - name: Deploy to Int
        run: |
          echo "Deploying to Int..."

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: container_build
    steps:
      - name: Create Release
        run: |
          echo "Creating a release..."

  deploy_to_qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: [deploy_to_dev, deploy_to_int, create_release]
    steps:
      - name: Deploy to QA
        run: |
          echo "Deploying to QA..."

  deploy_to_prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: [deploy_to_qa]
    steps:
      - name: Deploy to Prod
        run: |
          echo "Deploying to Prod..."
