name: Build and Deploy

on: 
  workflow_dispatch:

jobs:
  app-build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Compile
        run: |
          echo "Compiling the application..."
      
  container-build:
    name: Build Container
    runs-on: ubuntu-latest
    needs: app-build
    steps:
      - name: Build Docker Image
        run: |
          echo "Building the Docker image..."
  
  deploy-to-dev:
    name: Deploy to Dev 
    runs-on: ubuntu-latest
    needs: container-build
    steps:
      - name: Deploy to Dev
        run: |
          echo "Deploying to Dev..."

  deploy-to-int:
    name: Deploy to Int
    runs-on: ubuntu-latest
    needs: container-build
    steps:
      - name: Deploy to Int
        run: |
          echo "Deploying to Int..."

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: container-build
    if: ${{ github.ref == 'refs/heads/release/**' }}
    steps:
      - name: Create Release
        run: |
          echo "Creating a release..."

  deploy-to-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: [deploy-to-dev, deploy-to-int, create-release]
    steps:
      - name: Deploy to QA
        run: |
          echo "Deploying to QA..."

  deploy-to-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: [deploy-to-qa]
    steps:
      - name: Deploy to Prod
        run: |
          echo "Deploying to Prod..."
