name: Deploy a Release

on: 
  workflow_dispatch:
  push: 
    branches: # Remember to enforce this in the environment protection rules
      - "release/**"
      - "hotfix/**"
    paths:
      - "**"
      - "!README.md"
      - "!.gitignore"
      - "!.github/**"

jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
