name: Deploy a Feature
on: 
  workflow_dispatch:
  push: 
    branches:
      - "develop"
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"
      - "!**-alpha"
    paths:
      - "**"
      - "!README.md"
      - "!.gitignore"
      - "!.github/**"

jobs:
  build:
    uses: ./.github/workflows/publish.yaml
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying the application..."
        shell: bash 
