name: Deploy a Feature
on: 
  workflow_dispatch:
  push: 
    branches:
      - "develop"
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"
      - "!**-alpha"
    paths:
      - "**"
      - "!README.md"
      - "!.gitignore"
      - "!.github/**"

jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
