name: Deploy a Release

on: 
  workflow_dispatch:
  push: 
    branches: # Remember to enforce this in the environment protection rules
      - "release/**"
      - "hotfix/**"
    paths:
      - "**"
      - "!README.md"
      - "!.gitignore"
      - "!.github/**"

jobs:
  build:
    uses: ./.github/workflows/publish.yaml
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: protected
    steps:
      - name: Deploy
        run: echo "Deploying the application..."
        shell: bash 
