name: Release

on: 
  workflow_dispatch:
  push: 
    branches: # Remember to enforce this in the environment protection rules
      - main
    paths:
      - "**"
      - "!README.md"
      - "!.gitignore"
      - "!.github/**"

jobs:
  build:
    uses: ./.github/workflows/publish.yaml
  
  deploy:
    name: Deploy with Needs
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying the application $RND..."
        shell: bash 
        env:
          RND: ${{ needs.build.outputs.output-1 }}
  
  notify:
    name: Notify without Needs
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Notify
        run: echo "Notifying the team $RND..."
        shell: bash
        env:
          RND: ${{ needs.build.outputs.output-1 }}
